name: Deploy FastAPI to Lambda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt -t package/ --platform manylinux2014_aarch64 --only-binary=:all:
        cp -r app package/
        cp lambda_handler.py package/
    
    - name: Create deployment package
      run: |
        cd package
        zip -r ../deployment-package.zip .
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.JOUHOU_NAVI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.JOUHOU_NAVI_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.JOUHOU_NAVI_AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.JOUHOU_NAVI_AWS_LAMBDA }} \
          --zip-file fileb://deployment-package.zip
    
    - name: Wait for update
      run: |
        aws lambda wait function-updated \
          --function-name ${{ secrets.JOUHOU_NAVI_AWS_LAMBDA }}